<?php
require_once __DIR__ . '/../config/app.php';

if (!is_logged_in() || $_SESSION['user_role'] !== 'Student') {
    redirect('/login.php');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf_token();
    $question = trim($_POST['question'] ?? '');

    if (!empty($question)) {
        // Save user's question
        $stmt = $pdo->prepare("INSERT INTO ai_tutor (user_id, context) VALUES (?, ?)");
        $stmt->execute([$_SESSION['user_id'], "User: " . $question]);

        // Simulate AI Response securely through pure PHP/MySQL insertion
        $simulated_response = "AI: That's a great question about '" . htmlspecialchars($question) . "'. Since this is a local environment, I am a simulated response. In production, this text would be generated by the connected LLM API.";

        $stmt = $pdo->prepare("INSERT INTO ai_tutor (user_id, context) VALUES (?, ?)");
        $stmt->execute([$_SESSION['user_id'], $simulated_response]);

        set_flash_message('success', 'The AI Tutor has responded.');
        redirect('/student/ai-tutor.php');
    }
}

// Fetch chat history
$stmt = $pdo->prepare("SELECT context, created_at FROM ai_tutor WHERE user_id = ? ORDER BY created_at ASC");
$stmt->execute([$_SESSION['user_id']]);
$chats = $stmt->fetchAll();

require_once __DIR__ . '/../includes/header.php';
?>
<div style="display: flex; gap: 20px; flex-wrap: wrap;">
    <?php require_once __DIR__ . '/../includes/student_sidebar.php'; ?>
    <div class="dashboard-content card" style="flex: 3; min-width: 300px; display: flex; flex-direction: column;">
        <h2>Your AI Learning Assistant</h2>
        <p>Ask anything about your courses, code problems, or concepts you are struggling with.</p>

        <div class="chat-history" style="flex: 1; background: var(--bg-color); padding: 15px; border-radius: 8px; margin: 20px 0; max-height: 400px; overflow-y: auto;">
            <?php if (empty($chats)): ?>
                <p class="text-center" style="color: gray;">No history yet. Say hello!</p>
            <?php else: ?>
                <?php foreach ($chats as $chat): ?>
                    <?php
                    $is_user = strpos($chat['context'], 'User:') === 0;
                    $align = $is_user ? 'text-align: right;' : 'text-align: left;';
                    $bg = $is_user ? 'background: var(--primary-color); color: white;' : 'background: #e9ecef; color: #333;';
                    $text = preg_replace('/^(User:|AI:)\s*/', '', h($chat['context']));
                    ?>
                    <div style="<?= $align ?> margin-bottom: 15px;">
                        <div style="display: inline-block; padding: 10px 15px; border-radius: 15px; max-width: 80%; <?= $bg ?>">
                            <?= nl2br($text) ?>
                        </div>
                        <div style="font-size: 0.8rem; color: gray; margin-top: 5px;">
                            <?= date('M d, H:i', strtotime($chat['created_at'])) ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <form method="POST" action="ai-tutor.php" style="display: flex; gap: 10px;">
            <input type="hidden" name="csrf_token" value="<?= generate_csrf_token() ?>">
            <input type="text" name="question" placeholder="Ask a question..." required style="flex: 1; padding: 10px; border: 1px solid var(--border-color); border-radius: 4px;">
            <button type="submit" class="btn btn-primary">Ask AI</button>
        </form>
    </div>
</div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>